# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Calculator Pro' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Calculator Pro
  pod 'IQKeyboardManagerSwift'

  target 'Calculator ProTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Calculator ProUITests' do
    # Pods for testing
  end

end
